### PR TITLE
Remove jsonx

### PR DESCRIPTION
**Pull request by zmstone**
This is the first PR for 2.0.

Will send more pull requests (will try to keep them small) including:

* Replace mochijson3 with jiffy (which is fast (nif), published to erlang.mk and hex)
* Unify string encode/decode (allow `[byte()] | binary()` as encoders input, but only produce `binary()` from decoders)
* Remove deprecated APIs, change JSON decoder default decode result from wrapped to unwrapped
* Change enum symbols to `binary()`
* Change to `binary()` type names
* Change to `binary()` record field names
* Generate encoder/decoder code from schema store, compile, reload beam on the fly.

### CODE REVIEW

**Comment by comtihon** [comment]
From my point of view you should use https://github.com/sile/jsone instead. 
It is not nif and quite fast.

**Comment by zmstone** [comment]
i agree it's a good one.
however another reason i didn't mention is the popularity 
often a user have to pull in multiple json libraries implicitly from different dependencies.
e.g. we don't want to add yet another json library to kred

**Comment by comtihon** [comment]
As for kred deps, I look forward to moving all kdb and its deps to another repo and then, to another service, where we will have only one json dep - dep of erlavro.
jiffy is a nif and it is it's main disadvantage. If we think of all present kred's architecture - this can cause some problems with scalability on a high load.

**Comment by zmstone** [comment]
kred is just an example of multiple JSON libraries in one system.
I do not want to get in to any details in that regard on github.

we have used jsonx to produce three-digits mega-bytes payload.
it perhaps related to some scheduler issues when running in otp R16,
but it turned out to be pretty good since otp-17.

I consider NIF the main advantage (not disadvantage)
Although I have no benchmark on jsone to support, but when
comparing to mochijson3 (see the '13 times faster' comment),
I don't think a fairly schedule pure-Erlang library which would take 13 times longer
would be a fair trade off to make over NIF.

**Comment by comtihon** [comment]
Here is the benchmark https://github.com/sile/jsone/blob/master/BENCHMARK.md
Nif drops vm, if unstable.
Nif blocks sheduler.
When using nif - you copy all erlang data inside nif, convert it to C data, process, convert to Erlang and return. Even if process on C is faster - if data is big enougth - there can be problems with blocking sheduler. And this problems will be very hard to catch, when running the synthetic tests. But such behaviour can prevent real system from normal working.
It is one of the reasons, programmers select lists:keyfind instead of proplists:get_value. On syntetic test lists are faster, because it is a nif. But on real system it can be a pain, difficult to find. Please, do not do it.

**Comment by zmstone** [comment]
the benchmarks look pretty cool. jsone then.
@id any input on this?

**Comment by id** [comment]
Agree on jsone. One more pure erlang library in kred won't hurt much. We can also start persuading other developers to start using jsone instead of other libraries.

**Comment by zmstone** [comment]
any comments on the chang set?

**Comment by comtihon** [comment]
No

**Comment by id** [comment]
You are not going to add jsone as a dependency?

**Comment by zmstone** [comment]
@id not in this pr.
this is only a small part of a full pull request for 2.0, which will be sent from 2.0-dev branch to master when all the small ones are merged.

**Pull request merged**
