### PR TITLE
For string types, accept atoms as values

### PR DESCRIPTION
**Pull request by davydog187**
This PR adds functionality that allows string fields to accept atoms as values. I'm not sure if this is controversial in Erlang, but in Elixir it is very common to encode atom values as strings. For example, https://hexdocs.pm/jason/Jason.html#encode/2 happily encodes atom values as strings.

You can refer to this test example as well: https://github.com/michalmuskala/jason/blob/v1.1.2/test/encode_test.exs#L51

This has come up several times in projects where we are storing values as atoms, and we have to rewrite the value before passing it to the Avro encoder.

- [x] Properly encode union types (Test is broken)

### CODE REVIEW

**Comment by davydog187** [comment]
If this change seems reasonable, I would appreciate some advice with how to fix this test I broke. I'm still getting used to Erlang 😅 

```
avro_binary_encoder_tests: encode_enum_properly_test...*failed*
in function avro_binary_encoder_tests:'-encode_enum_properly_test/0-fun-2-'/2 (/Users/dave/Development/erlavro/test/avro_binary_encoder_tests.erl, line 212)
in call from avro_binary_encoder_tests:encode_enum_properly_test/0 (/Users/dave/Development/erlavro/test/avro_binary_encoder_tests.erl, line 212)
in call from eunit_test:'-mf_wrapper/2-fun-0-'/2 (eunit_test.erl, line 273)
in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71)
in call from eunit_proc:run_test/1 (eunit_proc.erl, line 510)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 335)
in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 493)
in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 435)
**error:{assertEqual,[{module,avro_binary_encoder_tests},
              {line,212},
              {expression,"Encoded1"},
              {expected,[[2],<<>>]},
              {value,[[0],["\b",<<"null">>]]}]}
  output:<<"">>
```

**Comment by davydog187** [comment]
@zmstone I fixed the tests here. I needed to add an additional check to make sure that `nil` and `null` were not being converted to strings.

**Comment by davydog187** [comment]
Done @mikpe I would appreciate a publish to hexpm once this gets merged. Thank you so much!

**Comment by davydog187** [comment]
@mikepe I do not have merge privileges, you’ll have to do it for me

**Comment by k32** [comment]
Hi @davydog187 ,

Thanks for your PR. Could you please elaborate the usecase. Is it meant as a convenience feature?
I think implicit type casting  in general should be avoided, as it tends to introduce sneaky bugs and unexpected behaviour.

**Comment by davydog187** [comment]
Hello @k32, thank you for taking the time to look at this PR. As mentioned, encoding atoms as strings is ubiquitous in Elixir. You can reference the example in the PRs description for an example.

When I wrote this PR, I wasn’t sure if the same was true in Erlang. However, it seems that https://github.com/sile/jsone/blob/master/README.md also takes the same approach to encode atoms as string values.

You mention that implicit type casting generates subtle bugs. While I do not disagree with you, there is a very big difference between casting and encoding. 

I am happy to find more examples of this behavior in the BEAM ecosystem, but so far all evidence points to this change being normal behavior for an encoding library.

**Comment by davydog187** [comment]
As for the use case, without this feature our application code has to do a pass on each data structure passed to the encoder to convert atoms to strings. This is not just a convenience but especially for nested structures, it is additional overhead.

**Comment by mikpe** [comment]
I personally have no problem with this change.  The code sits in what would be an error path, so there's no performance argument against it, and semantically we already allow Erlang strings (lists of characters) as well as binaries to map to strings, so allowing atoms too is entirely reasonable (otherwise we should disallow binaries).

**Comment by k32** [comment]
What worries me is that now certain atoms will have special semantics (`nil`, `null`), and _if_ someone depended on the error path (e.g. relied on `undefined` atom causing error), then we break their assumptions, so this is not a BWC change.

**Comment by davydog187** [comment]
Is `undefined` another edge case that we should add?

**Comment by davydog187** [comment]
In Elixir, I would solve this problem much differently. I would add a protocol for Avro encoder, and allow the consumer of the library to do define how they want structs/terms to be encoded

**Comment by zmstone** [comment]
we made it clear (in README) that only `null` is null (now `nil` is also null, but reasonable),
some library had a bug, generated `<<"null">>` as default value for record fields, a patch was made to allow it, that is all.

IMO. `undefined` is a value, some Erlang programers may not agree,
however, having to argue is already a sign of `undefined` being abused.
(similarly, we had to use atom `no_value` instead of `undefined` in some cases).

**Comment by davydog187** [comment]
Is there anything else I should resolve here?

**Comment by zmstone** [comment]
i think it’s good to merge

**Comment by davydog187** [comment]
Great! Can I have one of the maintainers merge for me?

**Comment by k32** [comment]
Don't we want to bump minor version for this fix (i.e. `2.9.0`), rather than patch version? @mikpe @zmstone

**Comment by davydog187** [comment]
@k32 good call. I changed to `2.9.0` and also updated the `vsn`

**Comment by k32** [comment]
Thank you!

**Pull request merged**
