### PR TITLE
Fix bytes and fixed JSON value decode

### PR DESCRIPTION
**Pull request by zmstone**
fixes https://github.com/klarna/erlavro/issues/126

### CODE REVIEW

**Comment by mikpe** [comment]
Ping @jesperes -- can you give this a spin in Kred CI?

**Comment by juanperi** [comment]
I gave this a try in my codebase and it works!
Thank you!

**Comment by zmstone** [comment]
ping @mikpe @jesperes

**Comment by mikpe** [comment]
Tested internally, looks good.
(Sorry it took so long, but vacations and internal reorg made this fall between the cracks.)

**Pull request merged**
